Ci / Split tasks to avoid testing issues
WordPress/wp-feature-notifications pull request #202
Opened 2023-04-01 20:50 UTC by erikyo

## What?
We update ci to separate build tasks with test tasks

## Why?
With the new setup we need composer to build the autoload.php file before testing, otherwise the autoloaded files are missing

## How?
Three files representing the three tasks were created, and in the testing one all the tests were merged
(bonus) added the os testing for node
removed -> php 7.3

2023-04-01 22:07 UTC, johnhooks requested changes
@erikyo do you think a workflow to run `npm run lint:js` is a good idea?

2023-04-01 22:07 UTC, johnhooks commented on .github/workflows/test-suite.yml
> +      run: npm install
This will use the lock file and throw an error if it needs to be updated by a PR.

```suggestion
      run: npm ci
```

2023-04-01 22:07 UTC, johnhooks commented on .github/workflows/node-build.yml
>        - run: npm install
```suggestion
      - run: npm ci
```

2023-04-01 22:07 UTC, johnhooks commented on .github/workflows/test-suite.yml
> +      run: wp-env start
```suggestion
      run: npm run wp-env:start
```

2023-04-01 22:07 UTC, johnhooks commented on .github/workflows/test-suite.yml
> +      run: npm -g i @wordpress/env
This shouldn't be necessary because `@wordpress/env` is a dev dependency now.

2023-04-01 22:21 UTC, erikyo commented
> @erikyo do you think a workflow to run npm run lint:js is a good idea?

the linting is something i prefer to fire before the ci, for example with a githook before commit

2023-04-01 22:26 UTC, johnhooks approved these changes

2023-04-01 22:52 UTC, johnhooks requested changes

2023-04-01 22:52 UTC, johnhooks commented on .github/workflows/test-suite.yml
> +      run: npm -g i @wordpress/env
@erikyo let's try this again.
```suggestion
```

2023-04-01 22:54 UTC, johnhooks approved these changes
LGTM!

2023-04-01 23:43 UTC, johnhooks approved these changes

2023-04-02 17:29 UTC, johnhooks commented
PR #213 proposes the same functionality, but extracts the environment setup into custom actions.

2023-04-02 17:33 UTC, closed without merging