239 Contributing docs
WordPress/wp-feature-notifications pull request #242
Opened 2023-04-05 13:50 UTC by Sephsekla

## What?

## Why?

Addresses #239 

## How?

## Testing Instructions

## Screenshots or screencast

2023-04-05 17:17 UTC, johnhooks commented
I think the initial, "how do you get connected" section is still very effective. 

It would be helpful to define a roadmap and explain where the current focus is. This probability doesn't belong in the CONTRIBUTING.md, but linking to where to find that information could direct new contributors towards the areas we need help (possibly linking to a project board). The issues list is, by its nature, rather unorganized and hard to look at as a newcomer a make sense of the priorities.

List the current maintainers and who has the authority to merge pull requests. 

What are the criteria for accepting pull requests:

- bugs: merged as quickly as possible
- refactors: merged if deemed necessary by the maintainers
- features: first considered whether or not it fits the project, if determined to fit with the projects goals, it’s placed into the project board, into the system and when complete is merged when it fits with the release schedule.

I'm pretty new to this, so those are just ideas. It can be hard to tell sometimes in projects like this whether or not contributions are welcomed. Providing a "when contributing" section that lays out how someone should approach offering a new idea can give them confidence we want their input and have thought through the process.

2023-04-20 16:07 UTC, Sephsekla commented
@johnhooks there's still a lot that could be added here, but for now I'd like to get something merged and then we can get 0.2.0 out. What do you think?

2023-04-20 16:09 UTC, johnhooks requested changes
This looks great @Sephsekla, I think you did a great job explaining the process of the PR workflow. Only suggestion, could you add the `CONTRIBUTING.md` to the `.distignore` file?

2023-04-20 16:09 UTC, johnhooks commented on README.md
> +- Contributors: schlessera, psykro, raaaahman, danbilauca, Sephsekla, erikyo, JasonTheAdams, johnhooks
❤️ thanks!

2023-04-20 16:24 UTC, Sephsekla commented
I don't think it actually makes a difference to the release process now we're using wp-scripts, but it's at the very least complete.

2023-04-20 16:25 UTC, johnhooks approved these changes
LGTM!

2023-04-20 16:26 UTC, johnhooks commented
> I don't think it actually makes a difference to the release process now we're using wp-scripts, but it's at the very least complete.

@Sephsekla the only reason I thought to add it is because we have that file and might use it someday, we should either keep it up to date or remove it.

2023-04-20 16:28 UTC, merged