Release 0.2.0
WordPress/wp-feature-notifications pull request #294
Opened 2023-04-20 17:55 UTC by Sephsekla

## What?

Creating the 0.2.0 release! 🥳 

## Why?

## How?

## Testing Instructions

## Screenshots or screencast

2023-04-20 19:40 UTC, johnhooks requested changes
Should we remove all these instances of the word notify?

2023-04-20 19:40 UTC, johnhooks commented on .editorconfig
> +indent_style = space
Everything is currently tab based, this isn't being applied, the default for Wordpress ESLint and Prettier settings must be tabs

2023-04-20 19:40 UTC, johnhooks commented on includes/restapi/fake_api.json
> +			"src": "https://raw.githubusercontent.com/erikyo/wp-notify/design_implementation/src/images/i.svg"
@erikyo didn't  you mention wanting to remove this icon link?

2023-04-20 19:40 UTC, johnhooks commented on src/scripts/components/NoticeHubSectionHeader.js
> +import { clearNotifyDrawer } from '../utils/';
It's not necessary to change, but this is a remnant of the "Notify" naming.

2023-04-20 19:40 UTC, johnhooks commented on src/scripts/demo/index.js
> +		'clear-all-wp-notify'
More "Notify"

2023-04-20 19:40 UTC, johnhooks commented on src/scripts/demo/index.js
> +			window.wp.notify.clear( 'dashboard' );
More "Notify"

2023-04-20 19:40 UTC, johnhooks commented on src/scripts/index.js
> +export default notify;
Lots of "Notify"

2023-04-20 19:40 UTC, johnhooks commented on src/scripts/store/controls.js
> + * Fetches the wp-notify rest api endpoint for the specified endpoint
"Notify"

2023-04-20 19:40 UTC, johnhooks commented on src/scripts/store/selectors.js
> + * commonly it's fired when the NotifyArea is registered
"Notify"

2023-04-20 19:40 UTC, johnhooks commented on src/scripts/utils/index.js
> +export const clearNotifyDrawer = ( context ) => {
"Notify"

2023-04-20 19:40 UTC, johnhooks commented on src/scripts/utils/init.js
> +		 * @member {HTMLElement} notifyDash - the area that will host the notifications
"Notify"

2023-04-20 19:40 UTC, johnhooks commented on storybook/.storybook/manager.js
> +	theme: wpNotifyTheme,
"Notify"

2023-04-20 19:40 UTC, johnhooks commented on storybook/.storybook/preview.js
> +/** Wp-notify style */
"Notify"

2023-04-20 19:40 UTC, johnhooks commented on storybook/.storybook/wp-notify-theme.js
> +	brandTitle: 'WP-Notify storybook',
"Notify"

2023-04-20 19:40 UTC, johnhooks commented on storybook/stories/Dash-multiple.stories.jsx
> +/** Wp-notify style */
"Notify"

2023-04-20 19:40 UTC, johnhooks commented on storybook/stories/Dash-single.stories.jsx
> +		<div id="wp-notify-dashboard-notices" className="wrap">
"Notify"

2023-04-20 19:40 UTC, johnhooks commented on storybook/stories/Dash-single.stories.jsx
> +	source: '#WP-Notify',
"Notify"

2023-04-20 19:40 UTC, johnhooks commented on storybook/stories/Hub-single.stories.jsx
> +	source: '#WP-Notify',
"Notify"

2023-04-20 19:40 UTC, johnhooks commented on storybook/stories/docs/contributors/develop.md
> +You can use it for contributing to the WP Notify project, but you need to install it on your computer first. read the [prerequisites](https://developer.wordpress.org/block-editor/packages/packages-en
"Notify"

2023-04-20 19:40 UTC, johnhooks commented on includes/restapi/fake_api.json
> +		"source": "#WP-Notify",
"Notify"

2023-04-20 19:46 UTC, Sephsekla commented on .editorconfig
> +indent_style = space
I can't remember where this came from but I'm personally in favour of tabs for everything, we could maybe change it.

2023-04-20 19:48 UTC, Sephsekla commented
Good spot on all of these!

I suggest we open a PR into develop for those notify references, and maybe another one for the editorconfig.

2023-04-20 20:00 UTC, johnhooks commented on .editorconfig
> +indent_style = space
I agree tabs all day

2023-04-20 20:57 UTC, johnhooks approved these changes, later dismissed
LUSTT! (Let Us Ship This Thing)

2023-04-21 09:49 UTC, erikyo approved these changes
LGTM!

2023-04-21 12:33 UTC, johnhooks approved these changes

2023-04-21 12:42 UTC, merged