Adds development build instructions
WordPress/wp-feature-notifications pull request #81
Opened 2022-06-11 13:13 UTC by erikyo

this PR will adds the basic build instructions in order to get the development environment working.

2022-06-11 13:55 UTC, bacoords approved these changes
I agree with all of this. It makes a lot of sense to keep this in the main readme and continue updating it as the plugin evolves.

2022-06-16 07:00 UTC, Sephsekla requested changes

2022-06-16 07:00 UTC, Sephsekla commented on README.md
>  To get started, please take a look at our [project wiki](https://github.com/WordPress/wp-notify/wiki)
```suggestion
To get started, please take a look at our [project wiki](https://github.com/WordPress/wp-feature-notifications/wiki)
```

2022-06-16 07:00 UTC, Sephsekla commented on README.md
> +$ npm i && composer install
Given we now have a `.nvmrc` file for node, is it worth adding a line about this?

2022-06-16 09:31 UTC, erikyo commented on README.md
> +$ npm i && composer install
with the nvmrc file 🤔 my system automatically switches the node versions after entering into a folder with this file... this don't happens also to you? maybe because [this](https://github.com/nvm-sh/nvm#zsh)?

2022-06-16 10:04 UTC, erikyo commented on README.md
> +$ npm i && composer install
```suggestion
$ nvm use && npm i && composer install
```

2022-06-16 17:06 UTC, bacoords approved these changes
Makes sense.

2022-06-17 11:27 UTC, Sephsekla commented on README.md
> +$ npm i && composer install
Thanks for updating, I'm conscious of new contributors who aren't as familiar with all these tools really. Maybe the line about requiring node could expand on it:

```markdown
- [NodeJS](https://nodejs.org/en/download/). We recommend using [nvm](https://github.com/nvm-sh/nvm) to ensure a compatible node version.
```

2022-06-17 17:25 UTC, erikyo commented
hey @Sephsekla, just came to my mind we can add something like
`"postinstall": "npm run build"`
in order to trigger automatically the build command after `npm i` was done, In this way the first build process could be even simpler! What do you think?

2022-07-19 17:29 UTC, bacoords commented
@erikyo @Sephsekla Do we need additional work on this branch?

2022-07-19 18:46 UTC, erikyo commented
@bacoords, I think it's completed, those are just the instructions to build the dev environment nothing more!

2022-09-07 12:46 UTC, Sephsekla approved these changes

2022-10-07 10:46 UTC, merged